---
- name: journalmd dependencies installation
  hosts: journalmd
  become: true
  roles:
    - geerlingguy.mysql
    - geerlingguy.nginx

- name: journalmd installation
  hosts: journalmd
  become: true
  roles:
    - journalmd
