# - src: uzer.crontab
# - src: ocha.yarn
# - src: oefenweb.fail2ban
# - src: arillso.logrotate

- src: geerlingguy.mysql
- src: geerlingguy.nginx

- name: "journalmd" # name: "JournalMd.journalmd"
  src: "https://github.com/JournalMd/ansible-role-journalmd.git"
